### ISSUE TITLE
Add support firmware 16.0.0

### ISSUE THREAD

**Issue by impeeza** [SegFault42/sys-ftpd-ovl#2]
Hi, since Teslalibs changed for 16.0.0 the code must be updated and build again, I did try but Programming is not my strength and get lost. thanks for your work

**Comment by epicmartin7** [comment]
Here's an updated compiled build with 16.0.0 HOS Support!
[sys-ftpd-ovl-master.zip](https://github.com/SegFault42/sys-ftpd-ovl/files/10926554/sys-ftpd-ovl-master.zip)

**Comment by intelliaim** [comment]
> Here's an updated compiled build with 16.0.0 HOS Support! [sys-ftpd-ovl-master.zip](https://github.com/SegFault42/sys-ftpd-ovl/files/10926554/sys-ftpd-ovl-master.zip)

Thank you!

**Comment by ileathan** [comment]
Nice! Hope it works with 17.0.0 HOS - Yup I think it is! :)

**Comment by karasuhebi** [comment]
The version provided by @epicmartin7 still works on Firmware 18.0.1|Atmosphere 1.7.0. Thank you!

**Comment by SegFault42** [comment]
Hey guys ! 

I'm not working on the project anymore.

I will add this build to the release section 

thx to @epicmartin7
